# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField()),
                ('ladder_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Ladder')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('date_added', models.DateField(verbose_name='Date added')),
                ('inaccurate_flag', models.BooleanField(default=None)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Ladder')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_opponent', to='ladder.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_player', to='ladder.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('season_round', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Player'),
        ),
        migrations.AddField(
            model_name='ladder',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Season'),
        ),
    ]
