 version: '2'
 services:
   db:
     image: postgres
   api:
     build: api/
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./api/:/usr/src/app/
     ports:
       - "8000:8000"
     depends_on:
       - db